### ISSUE TITLE
GN not clear to lay users

### ISSUE THREAD

**Issue by nkrth** [vivaldi/Vivaldi-GN#1]
I found this: https://www.chromium.org/developers/gn-build-configuration

Still not clear what GN is. What is Ninja? What is a build system?

I'm just familiar with gcc, lex and similar compilers.

**Comment by YngveNPettersen** [comment]
Ninja is an alternative to Make. Please see  https://en.wikipedia.org/wiki/Make_(software) , https://en.wikipedia.org/wiki/Ninja_(build_system) and https://ninja-build.org/ for more information.

GN is a compiler that generates the configuration files for Ninja, primarily used by the Chromium project and downstream embedders of the the Chromium browser code.
