### ISSUE TITLE
armv7 support Linux for use in Termux on Android.

### ISSUE THREAD

**Issue by Austcool-Walker** [vivaldi/Vivaldi-GN#6]
I was wondering if Vivaldi will support armv7 so it can be used in Android Termux and other arm32 bit environments?

**Comment by YngveNPettersen** [comment]
Vivaldi is available for 32 and 64-bit ARM processors for Linux and Android, See https://vivaldi.com/download/ (Linux ARM 64 is not yet directly downloadable through that page) and https://vivaldi.com/android/ 

Note: This repo is only hosting some extensions Vivaldi made to the Chromium team's GN project generation tool. Vivaldi support is available via our website https://help.vivaldi.com/ .

**Comment by Austcool-Walker** [comment]
> Vivaldi is available for 32 and 64-bit ARM processors for Linux and Android, See https://vivaldi.com/download/ (Linux ARM 64 is not yet directly downloadable through that page) and https://vivaldi.com/android/
> 
> Note: This repo is only hosting some extensions Vivaldi made to the Chromium team's GN project generation tool. Vivaldi support is available via our website https://help.vivaldi.com/ .

My devices of Android have jank ROMs that are arm64 SOC with stupid armv7 ROMs please consider armv7 support do to many androids phoned and devices have ROMs build in armv7 firmware!...

**Comment by Austcool-Walker** [comment]
> > Vivaldi is available for 32 and 64-bit ARM processors for Linux and Android, See https://vivaldi.com/download/ (Linux ARM 64 is not yet directly downloadable through that page) and https://vivaldi.com/android/
> > Note: This repo is only hosting some extensions Vivaldi made to the Chromium team's GN project generation tool. Vivaldi support is available via our website https://help.vivaldi.com/ .
> 
> My devices of Android have jank ROMs that are arm64 SOC with stupid armv7 ROMs please consider armv7 support do to many androids phoned and devices have ROMs build in armv7 firmware!...

Let me clarify I want armv7 build desktop application variant for using inside of armv7 desktop Ubuntu.

**Comment by Austcool-Walker** [comment]
> Vivaldi is available for 32 and 64-bit ARM processors for Linux and Android, See https://vivaldi.com/download/ (Linux ARM 64 is not yet directly downloadable through that page) and https://vivaldi.com/android/
> 
> Note: This repo is only hosting some extensions Vivaldi made to the Chromium team's GN project generation tool. Vivaldi support is available via our website https://help.vivaldi.com/ .

Wait I read that wrong it already supports it!!! Sorry for bothering you consider the issue solved lol...
